Repository BrowseBox/browsebox-web, pull requests merged in 2023-04, with the labels that each got.

#80 Only return user data if user is found
  browsebox-backend/controllers/user-controllers.js
Labels: size/S

#82 Fixed fix
  browsebox-backend/controllers/user-controllers.js
Labels: size/XS

#83 starting work on chat
  browsebox-backend/server.js
  browsebox-backend/socketserver.js
  package-lock.json
  package.json
  src/App.js
  src/Components/Testing Compnents/SimpleNav.js
  src/Components/UserComponents/Chat.js
Labels: area:frontend, size/L

#84 Fixed connection error
  package.json
  src/Components/ItemComponents/CreateAd2.js
Labels: size/XS

#85 Buttoncreated
  package-lock.json
  package.json
  src/pages/Home/Home.jsx
Labels: size/M

#87 Some package.json fixes
  package.json
Labels: size/XS

#88 Get id of item added
  browsebox-backend/controllers/sale-controllers.js
Labels: area:backend, size/S

#90 optional fields for user update
  browsebox-backend/controllers/user-controllers.js
Labels: size/M

#95 Add chat implementation
  browsebox-backend/controllers/chatControllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/models/chatModels.js
  browsebox-backend/routes/chatRoutes.js
  browsebox-backend/socketserver.js
  src/App.js
  src/Components/ChatComponents/ChatLoading.js
  src/Components/ChatComponents/ChatLogics.js
  src/Components/ChatComponents/ChatProvider.js
  src/Components/ChatComponents/Chatbox.js
  src/Components/ChatComponents/Chatpage.js
  src/Components/ChatComponents/MyChats.js
  src/Components/ChatComponents/SingleChat.js
  src/Components/ChatComponents/styles.css
Labels: area:frontend, area:backend, size/XXL

#96 Upgraded iage URL size
  browsebox-backend/database/browsebox.sql
Labels: size/XS

#97 Ad stuff
  src/Components/ItemComponents/AdList.js
  src/Components/ItemComponents/Congratulations.js
  src/Components/ItemComponents/CreateAd2.js
  src/Components/ItemComponents/EditItemModal.js
  src/Components/ItemComponents/Navbar.js
  src/Components/ItemComponents/PictureBox.js
  src/Components/ItemComponents/ShowAds.js
  src/Components/ItemComponents/ViewAd.js
  src/Components/ItemComponents/ViewAdModal.js
  src/Media/No_Image_Available.jpg
  src/index.js
  src/pages/Home/Home.jsx
  src/pages/Item/Item.jsx
Labels: size/XL

#98 Edit Form
  src/pages/Edit/EditForm.jsx
  src/pages/Header/Header.jsx
  src/pages/Signup/SignupForm.jsx
Labels: size/M

#101 Added cascade
  browsebox-backend/database/browsebox.sql
Labels: size/S

#100 Card Item
  src/pages/Home/Home.jsx
  src/pages/Item/Item.jsx
Labels: size/L

#102 Adding favorites
  browsebox-backend/controllers/favorites-controller.js
  browsebox-backend/controllers/review-controllers.js
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/models/favorite.js
  browsebox-backend/routes/favorite-routes.js
Labels: size/L

#103 Update get sale by filter id SQL
  browsebox-backend/controllers/sale-controllers.js
Labels: size/XS

#104 Untested Chat - Uploading will test today
  browsebox-backend/controllers/chatControllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/routes/chatRoutes.js
  browsebox-backend/socketserver.js
  src/App.js
  src/Components/AdminDashboard/components/AdminPanel.js
  src/Components/ChatComponents/ChatLoading.js
  src/Components/ChatComponents/ChatLogics.js
  src/Components/ChatComponents/Chatbox.js
  src/Components/ChatComponents/Chatpage.js
  src/Components/ChatComponents/SingleChat.js
  src/Components/ItemComponents/Congratulations.js
  src/Components/ItemComponents/FavoriteList.js
  src/Components/ItemComponents/ShowFavorites.js
  src/Components/ItemComponents/ViewAdModal.js
  src/Components/Testing Compnents/ChatLoading.js
  src/Components/Testing Compnents/ChatLogics.js
  src/Components/Testing Compnents/CreateAd.component.js
  src/Components/Testing Compnents/PictureBox2.js
  src/Components/Testing Compnents/SingleChat.js
  src/Components/Testing Compnents/ViewAd.js
  src/Components/Testing Compnents/styles.css
  src/pages/Header/Header.jsx
Labels: area:frontend, area:backend, size/XXL

#108 Something wrong
  browsebox-backend/controllers/favorites-controller.js
  browsebox-backend/routes/favorite-routes.js
  browsebox-backend/server.js
  src/Components/ItemComponents/FavoriteList.js
  src/Components/Testing Compnents/ChatLoading.js
  src/pages/Item/Item.jsx
Labels: size/L

#109 Revert "Something wrong"
  browsebox-backend/controllers/favorites-controller.js
  browsebox-backend/routes/favorite-routes.js
  browsebox-backend/server.js
  src/Components/ItemComponents/FavoriteList.js
  src/Components/Testing Compnents/ChatLoading.js
  src/pages/Item/Item.jsx
Labels: size/L

#110 Images are working Favorites are not
  browsebox-backend/controllers/favorites-controller.js
  src/Components/ItemComponents/CreateAd2.js
  src/pages/Item/Item.jsx
Labels: size/L

#111 Got favouriting mostly working
  browsebox-backend/controllers/favorites-controller.js
  browsebox-backend/routes/favorite-routes.js
  browsebox-backend/server.js
  src/pages/Item/Item.jsx
Labels: size/L

#112 Abner's updates
  src/Components/ItemComponents/CreateAd2.js
Labels: size/M

#107 Reverted package.json changes.
  package-lock.json
  src/App.js
  src/Components/ItemComponents/Category.js
  src/Components/ItemComponents/Filters.js
  src/Components/ItemComponents/SearchBar.js
  src/Components/ItemComponents/ShowFavorites.js
  src/Components/ItemComponents/ShowFilteredAds.js
  src/Components/ItemComponents/ShowSearchedAds.js
  src/Components/ItemComponents/ViewAdModal.js
  src/pages/Header/Header.jsx
  src/pages/Home/Home.jsx
Labels: size/L

#113 Items already favourited will return 200
  browsebox-backend/controllers/favorites-controller.js
Labels: size/XS

#114 Favoriting items
  browsebox-backend/controllers/favorites-controller.js
  browsebox-backend/routes/favorite-routes.js
  src/Components/ItemComponents/CreateAd2.js
  src/Components/ItemComponents/FavoriteList.js
  src/Components/ItemComponents/ShowFavorites.js
  src/pages/Item/Item.jsx
Labels: size/M

#116 cards now wrap
  src/pages/Home/Home.jsx
  src/pages/Item/Item.jsx
Labels: size/S

#117 Fixed Views
  src/Components/ItemComponents/ShowFilteredAds.js
  src/Components/ItemComponents/ShowSearchedAds.js
Labels: size/XS

#118 favorites now show ad when clicked
  src/Components/ItemComponents/FavoriteList.js
Labels: size/S
