Repository BrowseBox/browsebox-web, pull requests merged in 2023-03, with the labels that each got.

#42 Updated fields
  browsebox-backend/database/browsebox.sql
Labels: size/S

#43 add search item, delete item, update item in in the backend
  browsebox-backend/controllers/sale-controllers.js
Labels: size/L

#44 Reviews
  browsebox-backend/controllers/review-controller.js
  browsebox-backend/controllers/user-controllers.js
Labels: area:backend, size/M

#45 Routed reviews
  browsebox-backend/controllers/review-controllers.js
  browsebox-backend/routes/review-routes.js
  browsebox-backend/server.js
Labels: size/S

#46 Delete by POST
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/routes/user-routes.js
Labels: size/XS

#47 let user can only update his own sales
  browsebox-backend/controllers/sale-controllers.js
Labels: size/M

#49 This is an update with The Admin Dashboard at 25% and working routes.
  package-lock.json
  package.json
  src/App.js
  src/Components/AdminDashboard/AdminDashboard.js
  src/Components/AdminDashboard/components/Sidebar.js
  src/Components/AdminDashboard/components/SidebarData.js
  src/Components/AdminDashboard/components/SubMenu.js
  src/Components/AdminDashboard/pages/Overview.js
  src/Components/AdminDashboard/pages/Reports.js
  src/Components/AdminDashboard/pages/Team.js
  src/Components/Testing Compnents/SimpleNav.js
  src/Components/Testing Compnents/TestPage1.js
  src/Components/Testing Compnents/TestPage2.js
Labels: size/L

#50 Added a table to view user info. Added tab to temp create user.
  package-lock.json
  package.json
  src/App.js
  src/Components/AdminDashboard/components/UserList.js
  src/Components/AdminDashboard/components/UserTableRow.js
  src/Components/Testing Compnents/SimpleNav.js
Labels: size/L

#51 add check for user to delete an item
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/routes/sale-routes.js
Labels: size/L

#52 Added Abner's stuff
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/routes/user-routes.js
  browsebox-backend/util/checkInput.js
  src/Components/AdminDashboard/components/UserList.js
Labels: size/S

#53 updated case in trigger
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/database/review_score_trigger.sql
Labels: area:database, size/S

#56 feat: basic layout of cards.
  src/App.js
  src/pages/Home/Home.jsx
  src/pages/Item/Item.jsx
Labels: size/L

#57 Added some functions
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/routes/sale-routes.js
  browsebox-backend/routes/user-routes.js
Labels: size/M

#58 Add school data to user controller
  browsebox-backend/controllers/user-controllers.js
Labels: size/S

#61 Edit create Sale, user can create a sale just with item name.
  browsebox-backend/controllers/sale-controllers.js
Labels: size/XS

#62 Can add filters to an item
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/routes/sale-routes.js
Labels: size/M

#63 Can remove a filter
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/routes/sale-routes.js
Labels: size/S

#54 Add image upload tests to front end
  src/Components/tests/ImageUpload.jsx
Labels: area:frontend, size/M

#64 This is an update to the CreateAd2.js and PictureBox.js.
  src/Components/ItemComponents/CreateAd2.js
  src/Components/ItemComponents/PictureBox.js
Labels: new, area:frontend, size/L

#69 Update server URL for Anusone
  src/Components/tests/ImageUpload.jsx
Labels: size/XS

#70 Finish create ad
  src/Components/ItemComponents/CreateAd2.js
  src/Components/ItemComponents/PictureBox.js
Labels: area:frontend, area:backend, size/L

#71 updated expected names
  browsebox-backend/controllers/sale-controllers.js
Labels: size/XS

#74 Fixed issues on backend with item creation
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/routes/sale-routes.js
Labels: area:backend, size/M

#75 updated delete
  browsebox-backend/controllers/sale-controllers.js
Labels: size/M

#76 Updated updateSales and can get sale by ID
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/routes/sale-routes.js
Labels: size/L

#77 MAJOR UPDATE: 1:n category:sale
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/database/populate.sql
  browsebox-backend/routes/sale-routes.js
Labels: area:backend, size/L

#79 This is a fairly robust update it cover:
  src/Components/ItemComponents/AdList.js
  src/Components/ItemComponents/Congratulations.js
  src/Components/ItemComponents/CreateAd2.js
  src/Components/ItemComponents/EditItemModal.js
  src/Components/ItemComponents/Navbar.js
  src/Components/ItemComponents/ShowAds.js
Labels: size/L
