Repository BrowseBox/browsebox-web, pull requests merged in 2023-01, with the labels that each got.

#1 Add DB files
  src/database/DATABASE.md
  src/database/browsebox.sql
  src/database/review_score_trigger.sql
Labels: area:database, area:backend

#3 Implement Github Actions
  .github/workflows/ci.yml
  browsebox-web.code-workspace
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: size/L, area:tooling

#4 added material ui
  package-lock.json
  package.json
Labels: area:backend, size/XS

#5 File structure changes
  browsebox-backend/database/DATABASE.md
  browsebox-backend/database/browsebox.sql
  browsebox-backend/database/review_score_trigger.sql
  browsebox-backend/server.js
  browsebox-backend/util/datapool.js
  package.json
  src/App.test.js
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: size/M

#6 Add missing dependencies
  package-lock.json
  package.json
Labels: area:backend, size/XS

#7 Add dockerfile and environment documentation
  Dockerfile
  README.md
Labels: area:documentation, area:database, area:backend, area:tooling, size/M

#8 Add .editorconfig file to enforce coding style
  .editorconfig
Labels: area:tooling, size/XS

#9 deleted unneeded files
  src/App.css
  src/App.js
  src/logo.svg
Labels: area:frontend, size/M

#10 User class
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/models/user.js
  browsebox-backend/server.js
  package-lock.json
  package.json
Labels: size/M

#11 This was a test.!
  src/Components/test
Labels: size/XS

#13 db hotfix
  browsebox-backend/database/browsebox.sql
Labels: area:database, size/XS

#12 Start user controller
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/models/user.js
  browsebox-backend/routes/user-routes.js
  browsebox-backend/server.js
Labels: area:backend, size/M

#15 Test branch
  .idea/.gitignore
  .idea/browsebox-web.iml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/App.js
  src/Components/CreateUser.component.js
  src/Components/CreateUserForm.component.js
  src/Components/LoginUserForm.component.js
Labels: area:frontend, size/L

#16 Work on user
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/server.js
  package.json
Labels: area:backend, size/M

#17 Fix dependency conflict
  package-lock.json
  package.json
Labels: area:frontend, area:backend, size/XS

#19 wpi: worked on header & file structure
  .prettierrc
  src/App.js
  src/index.css
  src/pages/Header/Header.jsx
Labels: size/M

#20 I believe the form to play nice and send request to backend. Still ne…
  package-lock.json
  package.json
  src/App.js
  src/Components/Testing Compnents/DeleteUserTest.component.js
  src/Components/UserComponents/CreateUser.component.js
  src/Components/UserComponents/CreateUserForm.component.js
  src/Components/UserComponents/LoginUser.component.js
  src/Components/UserComponents/LoginUserForm.component.js
  src/Components/test
Labels: area:frontend, size/L

#22 deleted robots.txt
  public/robots.txt
Labels: area:frontend, size/XS
