Repository BrowseBox/browsebox-web, pull requests merged in 2023-02, with the labels that each got.

#23 Add user backend - done
  README.md
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/database/browsebox.sql
  browsebox-backend/server.js
  package-lock.json
  package.json
  src/Components/UserComponents/CreateUser.component.js
Labels: area:backend, size/M

#24 Add base components for item creation
  src/Components/CreateUser.component.js
  src/Components/CreateUserForm.component.js
  src/Components/ItemComponents/AdDetail.component.js
  src/Components/ItemComponents/ContactInformation.component.js
  src/Components/ItemComponents/LocationInformation.component.js
  src/Components/ItemComponents/MediaInformation.component.js
  src/Components/ItemComponents/PriceInformation.component.js
  src/Components/LoginUserForm.component.js
Labels: area:frontend, size/XL

#27 Daniel's Updates
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/models/sale.js
  browsebox-backend/routes/sale-routes.js
  browsebox-backend/routes/user-routes.js
  browsebox-backend/server.js
  src/Components/Testing Compnents/DeleteUserTest.component.js
  src/Components/UserComponents/LoginUser.component.js
Labels: area:backend, size/L

#28 This should bring the main up to date with both items and user forms …
  src/App.js
  src/Components/ItemComponents/CreateAd.component.js
  src/Components/ItemComponents/CreateItemForm.js
  src/Components/Testing Compnents/AdDetail.component.js
  src/Components/Testing Compnents/ContactInformation.component.js
  src/Components/Testing Compnents/LocationInformation.component.js
  src/Components/Testing Compnents/MediaInformation.component.js
  src/Components/Testing Compnents/PriceInformation.component.js
Labels: size/L

#29 Update users
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/routes/user-routes.js
Labels: size/M

#30 feat: signup & login modals
  package-lock.json
  package.json
  src/App.js
  src/pages/Header/Header.jsx
  src/pages/Login/LoginForm.jsx
  src/pages/Login/LoginModal.jsx
  src/pages/Signup/SignupForm.jsx
  src/pages/Signup/SignupModal.jsx
Labels: size/L

#31 added henry's changes
  browsebox-backend/controllers/user-controllers.js
Labels: size/M

#32 Form integration
  src/pages/Login/LoginForm.jsx
  src/pages/Login/LoginModal.jsx
  src/pages/Signup/SignupForm.jsx
  src/pages/Signup/SignupModal.jsx
Labels: size/L

#33 Updated a console log
  browsebox-backend/controllers/user-controllers.js
Labels: size/XS

#34 sign in by email
  browsebox-backend/controllers/user-controllers.js
Labels: size/S

#35 fix authenticate
  browsebox-backend/controllers/user-controllers.js
Labels: size/M

#36 fixed login
  browsebox-backend/controllers/user-controllers.js
Labels: size/XS

#37 feat: login and signup form works
  package-lock.json
  package.json
  src/pages/Login/LoginForm.jsx
  src/pages/Signup/SignupForm.jsx
Labels: size/M

#39 feat: user can edit their profile
  browsebox-backend/controllers/user-controllers.js
  src/App.js
  src/pages/Edit/Edit.jsx
  src/pages/Header/Header.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/LoginForm.jsx
  src/pages/Login/LoginModal.jsx
Labels: size/XL

#40 feat: fixed react-yup
  README.md
  package-lock.json
  package.json
  src/App.js
  src/pages/Edit/Edit.jsx
  src/pages/Header/Header.jsx
  src/pages/Signup/SignupForm.jsx
  src/pages/Signup/SignupModal.jsx
Labels: size/M

#41 Validation
  browsebox-backend/controllers/sale-controllers.js
  browsebox-backend/controllers/user-controllers.js
  browsebox-backend/util/checkInput.js
Labels: area:backend, size/L
